"""Copy accepted evergreen official source URLs into public event JSON."""

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parent
DEFAULT_EVERGREEN = ROOT / "data/evergreen_events.json"
DEFAULT_PUBLIC = ROOT / "data/public/events_public.json"
DEFAULT_PUBLIC_JS = ROOT / "data/public/events_public.js"

EXCLUDED_URLS = {
    "https://tsukijihongwanji.jp/news/10279/",
    "https://www.city.setagaya.lg.jp/documents/891/163gou_2.pdf",
}


def read_json(path):
    with Path(path).open(encoding="utf-8") as handle:
        return json.load(handle)


def write_json(path, data):
    with Path(path).open("w", encoding="utf-8") as handle:
        json.dump(data, handle, ensure_ascii=False, indent=2)
        handle.write("\n")


def write_public_js(path, events):
    with Path(path).open("w", encoding="utf-8") as handle:
        handle.write("// Auto-generated by export_public_events.py. Do not edit by hand.\n")
        handle.write("const EVENTS = ")
        json.dump(events, handle, ensure_ascii=False, indent=2)
        handle.write(";\n")


def norm(text):
    return re.sub(r"[^0-9A-Za-zぁ-んァ-ン一-龥]", "", text or "").lower()


def source_item(url, source_type):
    if source_type == "hp":
        return {"label": "告知HPあり", "url": url, "kind": "web"}
    return {"label": "公式告知あり", "url": url, "kind": "official"}


def source_urls(row):
    urls = []
    seen = set()
    for url in row.get("official_sources") or []:
        if not url or url in EXCLUDED_URLS or url in seen:
            continue
        seen.add(url)
        urls.append(url)
    return urls


def target_names(row):
    names = [row.get("event_name") or row.get("name") or ""]
    names.extend(row.get("aliases") or [])
    return [name for name in names if name]


def build_public_indexes(events):
    by_name_venue = {}
    by_name = {}
    by_venue = {}
    for event in events:
        names = {norm(event.get("name"))}
        for evidence in event.get("youtube_evidence") or []:
            if evidence.get("event_name"):
                names.add(norm(evidence.get("event_name")))
        venue = norm(event.get("venue"))
        by_venue.setdefault(venue, []).append(event)
        for name in names:
            if not name:
                continue
            by_name_venue.setdefault((name, venue), []).append(event)
            by_name.setdefault(name, []).append(event)
    return by_name_venue, by_name, by_venue


def choose_candidate(candidates, row):
    if not candidates:
        return None
    if len(candidates) == 1:
        return candidates[0]
    urls = " ".join(source_urls(row))
    if "2026" in urls:
        year_hits = [event for event in candidates if "2026" in (event.get("name") or "")]
        if len(year_hits) == 1:
            return year_hits[0]
    if "2025" in urls:
        year_hits = [event for event in candidates if "2025" in (event.get("name") or "")]
        if len(year_hits) == 1:
            return year_hits[0]
    upcoming = [event for event in candidates if event.get("public_category") == "upcoming"]
    if len(upcoming) == 1:
        return upcoming[0]
    return None


def find_public_event(row, by_name_venue, by_name, by_venue):
    venue = norm(row.get("venue"))
    for name in target_names(row):
        name_key = norm(name)
        candidate = choose_candidate(by_name_venue.get((name_key, venue), []), row)
        if candidate:
            return candidate, "name_venue"
    for name in target_names(row):
        candidate = choose_candidate(by_name.get(norm(name), []), row)
        if candidate:
            return candidate, "name_unique"
    for name in target_names(row):
        name_key = norm(name)
        candidates = [
            event for event in by_venue.get(venue, [])
            if name_key and (name_key in norm(event.get("name")) or norm(event.get("name")) in name_key)
        ]
        candidate = choose_candidate(candidates, row)
        if candidate:
            return candidate, "name_venue_fuzzy"
    return None, "unmatched"


def merge_sources(event, row):
    before = event.get("source_urls")
    if not isinstance(before, list):
        before = []
    existing = {item.get("url") for item in before if item.get("url")}
    merged = list(before)
    added = []
    for url in source_urls(row):
        if url in existing:
            continue
        item = source_item(url, row.get("official_source_type"))
        merged.insert(0, item)
        existing.add(url)
        added.append(item)
    event["source_urls"] = merged
    return added


def apply_sources(evergreen, events):
    rows = evergreen.get("events", evergreen if isinstance(evergreen, list) else [])
    by_name_venue, by_name, by_venue = build_public_indexes(events)
    summary = {"matched": 0, "updated": 0, "added_urls": 0, "unmatched": []}
    for row in rows:
        if not source_urls(row):
            continue
        event, reason = find_public_event(row, by_name_venue, by_name, by_venue)
        if not event:
            summary["unmatched"].append({
                "event_name": row.get("event_name") or row.get("name"),
                "venue": row.get("venue"),
                "urls": source_urls(row),
            })
            continue
        summary["matched"] += 1
        added = merge_sources(event, row)
        if added:
            summary["updated"] += 1
            summary["added_urls"] += len(added)
    return summary


def count_url_events(events):
    return sum(1 for event in events if any(source.get("url") for source in event.get("source_urls") or []))


def count_official_kind_events(events):
    return sum(
        1 for event in events
        if any(source.get("url") and source.get("kind") == "official" for source in event.get("source_urls") or [])
    )


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--evergreen", default=str(DEFAULT_EVERGREEN))
    parser.add_argument("--public", default=str(DEFAULT_PUBLIC))
    parser.add_argument("--public-js", default=str(DEFAULT_PUBLIC_JS))
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    evergreen = read_json(args.evergreen)
    events = read_json(args.public)
    before_url_events = count_url_events(events)
    before_official_events = count_official_kind_events(events)
    summary = apply_sources(evergreen, events)
    after_url_events = count_url_events(events)
    after_official_events = count_official_kind_events(events)
    summary.update({
        "events_with_source_url_before": before_url_events,
        "events_with_source_url_after": after_url_events,
        "events_with_official_kind_before": before_official_events,
        "events_with_official_kind_after": after_official_events,
    })
    if not args.dry_run:
        write_json(args.public, events)
        write_public_js(args.public_js, events)
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
