"""Second reviewed TokyoFesta 2026 public-event promotion batch."""

from pathlib import Path

import apply_tokyofesta_2026_public_events_batch as base


base.REPORT_JSON = Path("data/tokyofesta_2026_public_events_batch2_apply_report.json")
base.REPORT_MD = Path("data/tokyofesta_2026_public_events_batch2_apply_report.md")
base.REPORT_TITLE = "TokyoFesta 2026 public events batch 2 apply report"

base.EVENTS = [
    {
        "event_name": "自由が丘納涼盆踊り大会",
        "series_id": "ser_c7526cbcf3260dc3",
        "series_name": "自由が丘納涼盆踊り大会",
        "venue_id": "ven_e78a856a05226baa",
        "venue_aliases": ["自由が丘駅前ロータリー", "自由が丘駅前ロータリー 特設会場"],
        "area": "目黒区",
        "date_start": "2026-07-18",
        "date_end": "2026-07-20",
        "source_url": "https://tokyofesta.com/23ku/31825/",
        "public_intro": "自由が丘駅前ロータリー特設会場で開かれる、商店街主催の納涼盆踊り大会。",
        "detail": "2026年イベント掲載で、2026年7月18日(土)〜20日(月祝)18:00〜21:00、会場: 自由が丘駅前ロータリー 特設会場、主催: 自由が丘商店街振興組合、共催: 自由が丘住区青少年委員会を確認。関連URL: https://www.jiyugaoka-abc.com/",
    },
    {
        "event_name": "天王洲夏夜祭 with OKINAWA",
        "series_name": "天王洲夏夜祭 with OKINAWA",
        "venue": {
            "canonical_name": "アイルしながわ",
            "area": "品川区",
            "address": "東京都品川区東品川2丁目3-2付近",
            "access": "東京モノレール 天王洲アイル駅南口改札、りんかい線 天王洲アイル駅B出口から徒歩約5分",
            "scale": "中",
            "public_intro": "アイルしながわで開かれる、沖縄テーマの夏夜祭内の盆踊り系イベント。",
            "past_memo": "2026年は7月24日〜25日16:00〜21:00開催、雨天開催・荒天中止情報あり。",
            "source_url": "https://tokyofesta.com/23ku/31638/",
        },
        "venue_aliases": ["天王洲アイル アイルしながわ"],
        "area": "品川区",
        "date_start": "2026-07-24",
        "date_end": "2026-07-25",
        "source_url": "https://tokyofesta.com/23ku/31638/",
        "public_intro": "アイルしながわで開かれる、沖縄テーマの夏夜祭内の盆踊り系イベント。",
        "detail": "2026年イベント掲載で、2026年7月24日(金)〜25日(土)16:00〜21:00、会場: アイルしながわ、雨天開催・荒天中止を確認。東京Festaの盆踊りタグ掲載候補として登録。",
    },
    {
        "event_name": "大銀座盆踊り（ゆかたで銀ぶら）",
        "series_name": "大銀座盆踊り（ゆかたで銀ぶら）",
        "venue": {
            "canonical_name": "銀座中央通り",
            "area": "中央区",
            "address": "東京都中央区銀座1丁目〜8丁目付近",
            "access": "東京メトロ銀座駅・銀座一丁目駅・東銀座駅から徒歩圏内",
            "scale": "大",
            "public_intro": "銀座中央通りで開かれる、ゆかたで銀ぶら内の大銀座盆踊り。",
            "past_memo": "2026年は8月1日16:00〜20:00開催。大銀座盆踊りは銀座通りで開催予定。",
            "source_url": "https://tokyofesta.com/23ku/31190/",
        },
        "venue_aliases": ["銀座通り", "中央通り1丁目〜8丁目"],
        "area": "中央区",
        "date_start": "2026-08-01",
        "date_end": "2026-08-01",
        "source_url": "https://tokyofesta.com/23ku/31190/",
        "public_intro": "銀座中央通りで開かれる、ゆかたで銀ぶら内の大銀座盆踊り。",
        "detail": "2026年イベント掲載で、ゆかたで銀ぶらは2026年8月1日(土)16:00〜20:00、会場: 中央通り1丁目〜8丁目ほか、主催: 一般社団法人銀座通連合会を確認。大銀座盆踊りは16:00〜20:00、銀座通りで開催予定。関連URL: https://ginbura.ginza.jp/",
    },
    {
        "event_name": "道盆 DOUBON III",
        "series_name": "道盆 DOUBON",
        "venue": {
            "canonical_name": "渋谷道玄坂教会",
            "area": "渋谷区",
            "address": "東京都渋谷区道玄坂2丁目付近",
            "access": "渋谷駅から徒歩圏内",
            "scale": "小",
            "public_intro": "渋谷道玄坂教会で開かれる、DJ盆踊りスタイルの屋内イベント。",
            "past_memo": "2026年は8月8日20:00〜開催情報あり。",
            "source_url": "https://tokyofesta.com/23ku/31297/",
        },
        "venue_aliases": ["道玄坂教会 天井裏M", "道玄坂教会"],
        "area": "渋谷区",
        "date_start": "2026-08-08",
        "date_end": "2026-08-08",
        "source_url": "https://tokyofesta.com/23ku/31297/",
        "public_intro": "渋谷道玄坂教会で開かれる、DJ盆踊りスタイルの屋内イベント。",
        "detail": "2026年イベント掲載で、2026年8月8日(土)20:00〜、会場: 道玄坂教会 天井裏M、DJ: 珍盤亭娯楽師匠ほか、踊り手・和太鼓ありを確認。",
    },
    {
        "event_name": "神田明神納涼祭り",
        "series_id": "ser_782827501f1bd188",
        "series_name": "神田明神納涼祭り",
        "venue_id": "ven_19635dbca9225ae5",
        "venue_aliases": ["神田明神", "神田明神境内"],
        "area": "千代田区",
        "date_start": "2026-08-07",
        "date_end": "2026-08-09",
        "source_url": "https://tokyofesta.com/23ku/30945/",
        "public_intro": "神田明神境内で開かれる、アニソン盆踊りや民踊を含む納涼祭り。",
        "detail": "2026年イベント掲載で、2026年8月7日(金)〜9日(日)、会場: 神田明神、主催: 江戸総鎮守 神田明神を確認。1日目はアニソン盆踊り16:30〜20:30、2日目は千代田区民踊連盟、3日目は浜町音頭保存会。関連URL: https://www.nouryo-matsuri.com/",
    },
    {
        "event_name": "有明まつり",
        "series_name": "有明まつり",
        "venue": {
            "canonical_name": "有明ガーデン スポーツエンターテイメント広場",
            "area": "江東区",
            "address": "東京都江東区有明2丁目1-8",
            "access": "ゆりかもめ 有明駅から徒歩約4分、有明テニスの森駅から徒歩約3分、りんかい線 国際展示場駅から徒歩約6分",
            "scale": "中",
            "public_intro": "有明ガーデンで開かれる、有明地域のまつり内の盆踊り候補イベント。",
            "past_memo": "2026年は9月12日14:00〜20:30開催情報あり。",
            "source_url": "https://tokyofesta.com/23ku/31195/",
        },
        "venue_aliases": ["有明ガーデン"],
        "area": "江東区",
        "date_start": "2026-09-12",
        "date_end": "2026-09-12",
        "source_url": "https://tokyofesta.com/23ku/31195/",
        "public_intro": "有明ガーデンで開かれる、有明地域のまつり内の盆踊り候補イベント。",
        "detail": "2026年イベント掲載で、2026年9月12日(土)14:00〜20:30、会場: 有明ガーデン スポーツエンターテイメント広場、主催: 有明街づくりプロジェクトを確認。関連URL: https://www.aripro.tokyo/",
    },
    {
        "event_name": "新小岩北口盆踊りフェスタ",
        "series_name": "新小岩北口盆踊りフェスタ",
        "venue": {
            "canonical_name": "JR新小岩駅北口駅前広場",
            "area": "葛飾区",
            "address": "東京都葛飾区西新小岩1丁目付近",
            "access": "JR新小岩駅北口すぐ",
            "scale": "中",
            "public_intro": "JR新小岩駅北口駅前広場と新小岩北口商店街で開かれる盆踊りフェスタ。",
            "past_memo": "2026年は9月12日〜13日開催情報あり。",
            "source_url": "https://tokyofesta.com/23ku/30968/",
        },
        "venue_aliases": ["新小岩北口商店街", "JR新小岩駅北口駅前広場、新小岩北口商店街"],
        "area": "葛飾区",
        "date_start": "2026-09-12",
        "date_end": "2026-09-13",
        "source_url": "https://tokyofesta.com/23ku/30968/",
        "public_intro": "JR新小岩駅北口駅前広場と新小岩北口商店街で開かれる盆踊りフェスタ。",
        "detail": "2026年イベント掲載で、2026年9月12日(土)13:00〜20:30・13日(日)11:00〜19:30、会場: JR新小岩駅北口駅前広場、新小岩北口商店街、主催: 新小岩北口盆踊りフェスタ実行委員会を確認。関連URL: https://shinkoiwa06.1web.jp/",
    },
    {
        "event_name": "SHIBUYA MIYASHITA PARK BON DANCE",
        "series_name": "SHIBUYA MIYASHITA PARK BON DANCE",
        "venue_id": "ven_458974149d5a2766",
        "venue_aliases": ["MIYASHITA PARK 4階 渋谷区立宮下公園 芝生ひろば", "宮下公園"],
        "area": "渋谷区",
        "date_start": "2026-09-26",
        "date_end": "2026-09-27",
        "source_url": "https://tokyofesta.com/23ku/30742/",
        "public_intro": "MIYASHITA PARKの芝生ひろばで開かれる、渋谷カルチャーと盆踊りを組み合わせたイベント。",
        "detail": "2026年イベント掲載で、SHIBUYA MIYASHITA PARK BON DANCE 2026は2026年9月26日(土)〜27日(日)13:00〜21:00、会場: MIYASHITA PARK 4階 渋谷区立宮下公園 芝生ひろば、主催: 明治通り宮下パーク商店会、入場無料・雨天中止を確認。関連URL: https://miyashita-bondance.jp/",
    },
]


if __name__ == "__main__":
    base.main()
